blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/LazyKaddu/fractal-codec/discussions
    about: Please ask and answer questions here instead of filing an issue.
